### ISSUE TITLE
Large Scenes

### ISSUE THREAD

**Issue by kylepob** [lilygoli/SpotLessSplats#1]
Thank you for your work! I wanted to ask if you had recommended settings for large scenes or scenes that are non-object centric. Is there a combination of UBP/clustering or specific hyperparameters that you would recommend for datasets that cover large areas?

**Comment by lilygoli** [comment]
I would suggest to turn off UBP for scenes with less dense coverage of different areas in the input images. For clustering, we found MLP version usually works best, but classic clustering can provide more robustness if needed, at the cost of losing some useful information from the scene too. So I would start with MLP and no UBP and then adjust based on the results.

**Comment by kylepob** [comment]
Thanks, I'll start with the settings you recommended!

**Comment by NIZAHO** [comment]
> 我建议为输入图像中不同区域覆盖密度较低的场景关闭 UBP。对于聚类，我们发现 MLP 版本通常效果最好，但如果需要，经典聚类可以提供更多的健壮性，但代价是也会丢失场景中的一些有用信息。因此，我会从 MLP 开始，不使用 UBP，然后根据结果进行调整。

Hello! What should I do if I don't have enough memory for a large scene when using the MLP version, but I can use the AGG version. The following error message is reported:
[Parser] 872 images, taken by 1 cameras.
Scene scale: 2.162506700636682
Model initialized. Number of GS: 593453
/root/miniconda3/envs/gsplat/lib/python3.12/site-packages/torchmetrics/functional/image/lpips.py:325: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
  0%|                                                                                         | 0/30000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 1308, in <module>
    main(cfg)
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 1298, in main
    runner.train()
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 633, in train
    sf = torch.cat([sf, pos_enc], dim=0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.97 GiB. GPU 0 has a total capacity of 23.55 GiB of which 9.41 GiB is free. Including non-PyTorch memory, this process has 14.13 GiB memory in use. Of the allocated memory 13.59 GiB is allocated by PyTorch, and 68.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by lilygoli** [comment]
How many images does your scene include and what is your GPU memory size? Usually this code works fine with around 150-200 images of resolution <512. The main memory bottleneck is the semantic feature loading into the GPU memory. Make sure you are only loading training image features to save on the memory. If you still have memory issues, another solution can be projecting the semantic features to a lower dimensional space using PCA. Currently the features have a dimension of 1280, but they can be projected onto their first 500 components or so and still work reasonably well.

**Comment by NIZAHO** [comment]
> 您的场景包含多少张图像，您的 GPU 内存大小是多少？通常，此代码在 40GB 计算机上处理大约 150-200 张分辨率为 <512 的图像。主要的内存瓶颈是加载到 GPU 内存中的语义特征。确保您只加载训练图像特征以节省内存。如果你仍然有内存问题，另一种解决方案可能是使用 PCA 将语义特征投影到低维空间。目前，这些特征的维度为 1280，但它们可以投影到前 500 个左右的组件上，并且仍然运行良好。

感谢您的回复！问题已经得到解决

> How many images does your scene include and what is your GPU memory size? Usually this code works fine with around 150-200 images of resolution <512 on a 40GB machine. The main memory bottleneck is the semantic feature loading into the GPU memory. Make sure you are only loading training image features to save on the memory. If you still have memory issues, another solution can be projecting the semantic features to a lower dimensional space using PCA. Currently the features have a dimension of 1280, but they can be projected onto their first 500 components or so and still work reasonably well.

Thanks for your reply! The problem has been resolved

**Comment by luoshuiyue** [comment]
@NIZAHO Hi~ Can I ask you how to run through your own data set. I set the format of images/clutter000.jpg and sparse. Then run python spotless_trainer.py --data_dir [data directory] --data_factor 8 --result_dir [result directory] --loss_type robust --semantics --no-cluster --train_keyword "clutter" ,still many different errors. Could you please help me sort out the data processing flow?

**Comment by NIZAHO** [comment]
> @NIZAHO Hi~ Can I ask you how to run through your own data set. I set the format of images/clutter000.jpg and sparse. Then run python spotless_trainer.py --data_dir [data directory] --data_factor 8 --result_dir [result directory] --loss_type robust --semantics --no-cluster --train_keyword "clutter" ,still many different errors. Could you please help me sort out the data processing flow?

Sure. but this project is no longer maintained by me, so I can only tell it from memory. I remember that if you want to run your own dataset, you have to set the correct prefix according to the train_keyword and test_keyword, and then use sd_feature_extraction.ipynb to extract the feature map. Based on that, you can organize the file in the right way to train.

**Comment by luoshuiyue** [comment]
> > @NIZAHO Hi~ Can I ask you how to run through your own data set. I set the format of images/clutter000.jpg and sparse. Then run python spotless_trainer.py --data_dir [data directory] --data_factor 8 --result_dir [result directory] --loss_type robust --semantics --no-cluster --train_keyword "clutter" ,still many different errors. Could you please help me sort out the data processing flow?
> 
> Sure. but this project is no longer maintained by me, so I can only tell it from memory. I remember that if you want to run your own dataset, you have to set the correct prefix according to the train_keyword and test_keyword, and then use sd_feature_extraction.ipynb to extract the feature map. Based on that, you can organize the file in the right way to train.

Thank you for your reply！
