### ISSUE TITLE
Many errors occur while reproducing your setup

### ISSUE THREAD

**Issue by kalelpark** [lilygoli/SpotLessSplats#10]
Thank you for your research.  
However, in my experience reproducing your setup, I encountered several errors while preparing the dataset before training. 
Could you commit to an updated version?

![image](https://github.com/user-attachments/assets/a163c6dd-a104-48fb-825a-b80ae46fc956)

**Comment by lilygoli** [comment]
This seems like a problem with cameras. The prepare_data.py script only renames files according to our format. 
Nontheless, I am investigating the problems reported and will soon upload the datasets so it resolves any mismatch

**Comment by lilygoli** [comment]
please follow the thread in issue #11 for updates.

**Comment by kalelpark** [comment]
@lilygoli  Thanks I resolve it! :)
