### ISSUE TITLE
data prepare error

### ISSUE THREAD

**Issue by xiyufeng2** [lilygoli/SpotLessSplats#2]
Hello Author! When I use my own data(processed by Colmap) to run the reconstruction, file "prep_data.py" need a input for "split.json".   How to get it??

**Comment by lilygoli** [comment]
Hi!
There's no need to run prep_data.py for data that is prepared with Colmap, that is good to go as is.
The prep_data.py is specifically there for processing the format of the released NeRF On-the-go dataset.

**Comment by gujiaqivadin** [comment]
> Hi! There's no need to run prep_data.py for data that is prepared with Colmap, that is good to go as is. The prep_data.py is specifically there for processing the format of the released NeRF On-the-go dataset.

Thanks for your reply, but I want to know where is the code for using the updated "transforms.json" in the on-the-go dataset.

**Comment by lilygoli** [comment]
please look at #11 for any data format issues.
