### ISSUE TITLE
Errors due to version of python

### ISSUE THREAD

**Issue by yangfpths** [lilygoli/SpotLessSplats#3]
Hi, upon using custom dataset with colmap, i encountered an error which located in 
\scene_manager.py", line 199
Quaternion(np.array(map(float, data[1:5]))) 
Input quaternion should be a 3- or 4-vector. 
That happens when loading camera.txt. After checking this error , i found that in python2.x 
`np.array(map(float, data[1:5])) 
`gives a np array that could be processed, but in 3.x map returns a map object which raise this error. and after changing it to
`np.array(list(map(float, data[1:5])))
`it works smoothly, but later encounter another error
And using camera.bin raise another struct error, which i believe would not happen in python2.X. 
Could you please give a copy of your environment so that i could reproduce this result? Thank you!

**Comment by lilygoli** [comment]
Sure, I have a conda environment with python 3.9.19. The packages are detailed below:


name: gsplat
channels:
  - nodefaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.7.4=hbcca054_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.1=h4bc722e_2
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=71.0.4=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h0c530f3_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - cmake==3.30.2
      - colorlog==6.8.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.27.2
      - docstring-parser==0.16
      - embreex==2.17.7.post5
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.13.1
      - fonttools==4.53.1
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - gdown==5.2.0
      - grpcio==1.65.1
      - gsplat==1.0.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.2
      - idna==3.7
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jaxtyping==0.2.29
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lab==8.2
      - lazy-loader==0.4
      - lightning-utilities==0.11.6
      - lit==18.1.8
      - lxml==5.2.2
      - manifold3d==2.5.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nerfview==0.0.2
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==24.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycollada==0.8
      - pycolmap==0.0.1
      - pycparser==2.22
      - pygments==2.18.0
      - pyliblzfse==0.4.1
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.1
      - rtree==1.3.0
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - shapely==2.0.5
      - shtab==1.7.1
      - simplejson==3.19.2
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - svg-path==6.3
      - sympy==1.12
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - timm==0.6.7
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.0.1
      - torch-fidelity==0.3.0
      - torchaudio==2.4.0+cu118
      - torchmetrics==1.4.0.post0
      - torchvision==0.15.2
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.40.1
      - trimesh==4.4.3
      - triton==2.0.0
      - txt2tags==3.9
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - tyro==0.8.5
      - uri-template==1.3.0
      - urllib3==2.2.2
      - vhacdx==0.0.8.post1
      - viser==0.2.1
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xatlas==0.0.9
      - xxhash==3.4.1
      - yourdfpy==0.0.56
      - zipp==3.19.2
prefix: /opt/conda/envs/gsplat
