### ISSUE TITLE
Request data preprocessing scripts

### ISSUE THREAD

**Issue by zhangwenniu** [lilygoli/SpotLessSplats#4]
Hi, thanks for your great contribution for robust reconstruction. 

But I'm confused about how to train on my dataset, because I don't know exactly how RobustNeRF dataset is built. 

For example, when I get jpg images in the folder of 'data/test1/img_001.jpg', what steps should I do to get proper data formats to train the model? 

Looking forward to your kind reply.

**Comment by lilygoli** [comment]
Hi to use the SemanticParser for datasets like RobustNeRF, you need to arrange your data folder like below:

data
|_ images
|        |_ clean000.jpg
|         ...
|        |_ extra000.jpg
|         ...
|        |_ clutter000.jpg
|         ...
|_ sparse
        |_ 0
             |_ cameras.bin
             |_ points3D.bin
             |_ images.bin

The images have prefixes like "clean" for clean data and "extra" for test clean images and "clutter" for noisy images. You can have different prefixes and pass the prefix for train and test images to the training command. For example we use "clutter" prefix for training images and "extra" for test images, in the robust training scenario. We use "clean" for training for the idea clean set up in the paper (usually this is not available for custom real data so you can ignore it).

**Comment by zhangwenniu** [comment]
Thanks.

**Comment by luoshuiyue** [comment]
@zhangwenniu hi~Can I ask you how to run through your own data set. I set the format of images/clutter000.jpg and sparse. Then run `python spotless_trainer.py --data_dir [data directory] --data_factor 8 --result_dir [result directory] --loss_type robust --semantics --no-cluster --train_keyword "clutter"` ,still many different errors. Could you please help me sort out the data processing flow?

**Comment by lilygoli** [comment]
Can you please provide the error you get?

**Comment by ccxi1008** [comment]
> Hi to use the SemanticParser for datasets like RobustNeRF, you need to arrange your data folder like below:
> 
> ```
> data
> |_ images
> |         |_ clean000.jpg
> |          ...
> |         |_ extra000.jpg
> |          ...
> |         |_ clutter000.jpg
> |          ...
> |_ sparse
>           |_ 0
>                |_ cameras.bin
>                |_ points3D.bin
>                |_ images.bin
> ```
> 
> The images have prefixes like "clean" for clean data and "extra" for test clean images and "clutter" for noisy images. You can have different prefixes and pass the prefix for train and test images to the training command. For example we use "clutter" prefix for training images and "extra" for test images, in the robust training scenario. We use "clean" for training for the idea clean set up in the paper (usually this is not available for custom real data so you can ignore it).

Must I first rename  images and then run colmap? Cause I already have colmap results now but my images don't have prefix. I don't know if I rename the images, the sparse results can still work correctly or not? Or how can I don't use prefix?
