### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by NIZAHO** [lilygoli/SpotLessSplats#5]
Hello! What should a good form of data organization that can be used for spotless_trainer.py look like?

**Comment by lilygoli** [comment]
please look at the response in #4 and let me know if that answers the question.

**Comment by NIZAHO** [comment]
> 请查看 #4 中的回复，让我知道这是否回答了问题。

Thank you for your reply! If I use an image that doesn't contain the tags clean, extra, or clutter, will I not be able to use the spotless_trainer.py? Or somehow I can get these labels on my own training set

**Comment by NIZAHO** [comment]
> please look at the response in #4 and let me know if that answers the question.

Then I have another question, what is the difference between the simple_trainer.py function in the library and the gsplat library?Thanks again for your reply！

**Comment by lilygoli** [comment]
for your first question, the dataloader for our method assumes that your files are somehow "tagged", that means that each image has a special prefix, which then you can pass along to the training command with `--train_keyword` and `--test_keyword`. If all of your dataset is for training you can just rename the files to all have a specific prefix and pass that prefix as both train and test keyword. Although this might make running slow as your test set becomes big.
for your second question, there is no difference there, that is just a plain 3DGS trainer.

**Comment by NIZAHO** [comment]
> 对于您的第一个问题，我们方法的 DataLoader 假设您的文件以某种方式被“标记”，这意味着每张图像都有一个特殊的前缀，然后您可以使用 AND 将其传递给训练命令。如果所有数据集都用于训练，则只需将文件重命名为 all 具有特定前缀，并将该前缀作为 train 和 test 关键字传递。尽管这可能会随着测试集变大而使运行速度变慢。对于您的第二个问题，没有区别，只是一个简单的 3DGS 训练器。`--train_keyword``--test_keyword`

Thank you for answering my doubts, it is very valuable to me！

**Comment by NIZAHO** [comment]
> for your first question, the dataloader for our method assumes that your files are somehow "tagged", that means that each image has a special prefix, which then you can pass along to the training command with `--train_keyword` and `--test_keyword`. If all of your dataset is for training you can just rename the files to all have a specific prefix and pass that prefix as both train and test keyword. Although this might make running slow as your test set becomes big. for your second question, there is no difference there, that is just a simple 3DGS trainer.

Sorry to bother you again. What should I do if the error CUDA out of memory is reported, and is there a way to optimize the memory? Here are the relevant parameters when I trained:


--train-keyword frame --data_dir /usr/local/gaussian-splatting/convert360/trian_data/shenzhen2min --data_factor 1   --result_dir /usr/local/gaussian-splatting/convert360/trian_data/shenzhen2min/result --loss_type robust --semantics --no-cluster --train_keyword "clutter" --test_keyword "extra"  --disable-viewer
Warning: image_path not found for reconstruction
[Parser] 872 images, taken by 1 cameras.
Scene scale: 2.162506700636682
Model initialized. Number of GS: 593453
/root/miniconda3/envs/gsplat/lib/python3.12/site-packages/torchmetrics/functional/image/lpips.py:325: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
  0%|                                                                                         | 0/30000 [00:00<?, ?it/s]/root/miniconda3/envs/gsplat/lib/python3.12/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
  0%|                                                                                         | 0/30000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 1265, in <module>
    main(cfg)
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 1255, in main
    runner.train()
  File "/usr/local/SpotLessSplats/examples/spotless_trainer.py", line 627, in train
    sf = torch.cat([sf, pos_enc], dim=0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.97 GiB. GPU 0 has a total capacity of 23.55 GiB of which 9.21 GiB is free. Including non-PyTorch memory, this process has 14.33 GiB memory in use. Of the allocated memory 13.69 GiB is allocated by PyTorch, and 165.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
