### ISSUE TITLE
nerf_synthetic dataset support

### ISSUE THREAD

**Issue by liujie-zheng** [lilygoli/SpotLessSplats#6]
Hi there! Does this approach support datasets such as nerf_synthetic with train, test and transforms.json?

**Comment by liujie-zheng** [comment]
Also for the Nerf On-the-go dataset, do I need to run COLMAP on them before training (since sparse is missing)?

**Comment by lilygoli** [comment]
The [ semantic data parser](https://github.com/lilygoli/SpotLessSplats/blob/4aa06afc03b058bd1e64a411f44910b934fd8441/examples/datasets/colmap.py#L243) that we have included in the examples/datasets/colmap.py file is built on top of COLMAP parse. However it can easily be transferred to other type of parsers as it only adds semantic feature loading on top of the usual image and camera pose loading. The dataset format and naming should also follow the format described in #4.
For all the datasets that we use in the paper we have run COLMAP on them first.

**Comment by mazy1998** [comment]
Hi im having the same issue when I run my own COLMAP on the Nerf On-the-go dataset, it doesn't work, can you kindly give the CLI commands for running COLMAP for directory including the files, "images"-"SD"-"split.json" (given that I have ran prep_data.py already)

**Comment by mazy1998** [comment]
changing this code.

`            if type_ == 2 or type_ == "SIMPLE_RADIAL":
                params = np.array([cam.k1, 0.0, 0.0, 0.0], dtype=np.float32)
                camtype = "perspective" `

 seems to help, I added extra 0s to params as described here. 
 
 https://amroamroamro.github.io/mexopencv/matlab/cv.getOptimalNewCameraMatrix.html
